name: Go Deploy Build And Test 

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Prepare
        id: prep
        run: |
          TAG=latest
          IMAGE="go-dev"
          echo ::set-output name=tagged_image::${IMAGE}:${TAG}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile.dev.simple
          platforms: linux/amd64,linux/arm64/v8
          push: false
          load: true
          tags: ${{ steps.prep.outputs.tagged_image }}

  DockertTest:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - name: Pull Image
        run: |
          docker pull geneontology/go-devops-base:actions 

      - name: Provision and Test 
        run: |
          docker run --rm \
              -e GEN_SSH_KEYS=${{ vars.GEN_SSH_KEYS }}  -e AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} -e AWS_ACCESS_SECRET=${{ secrets.AWS_ACCESS_SECRET }} \
              -v ${{ github.workspace }}:/go-deploytesting -w /go-deploytesting -t geneontology/go-devops-base:actions ./run.sh
