name: Go Deploy Build And Test 

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 
  workflow_dispatch:

jobs:
  DockerBuild:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Prepare
        id: prep
        run: |
          TAG=latest
          IMAGE="go-dev"
          echo ::set-output name=tagged_image::${IMAGE}:${TAG}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile.dev.simple
          push: false
          load: true
          tags: ${{ steps.prep.outputs.tagged_image }}
