name: Go Deploy Build And Test 

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 
  workflow_dispatch:

env:
  tagged_image: geneontology/go-devops-base:cicd

jobs:
  DockerBuildAndTest:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile.dev.simple
          push: false
          load: true
          tags: ${{ env.tagged_image }}

      - name: List Images
        run: |
          docker image list | grep geneontology

      - name: Create Bash Script
        run: |
           cat <<EOF > run.sh |
           #!/bin/bash
           go-deploy -init --working-directory aws
           go-deploy --working-directory aws -w test-go-deploy -c config.yml.sample
           public_ip=`terraform -chdir=aws output -raw public_ip`
           echo $public_ip
           ssh -i /tmp/go-ssh ubuntu@$public_ip ls -l stage_dir/test_file
           ret=$?
           go-deploy --working-directory aws -w test-go-deploy -destroy
           exit $ret
           EOF
           chmod +x run.sh

      - name: Provision and Test
        run: |
          docker run --rm \
              -e GEN_SSH_KEYS=${{ vars.GEN_SSH_KEYS }}  -e AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} -e AWS_ACCESS_SECRET=${{ secrets.AWS_ACCESS_SECRET }} \
              -v ${{ github.workspace }}:/go-deploytesting -w /go-deploytesting -t ${{ env.tagged_image }} ./run.sh
